### model
model_name_or_path: /data/cth/saves/Qwen2.5-Math-7B/full/sft_curr_part2
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

# KL loss specific parameters
use_kl_loss: false  # enable the KL loss
kl_beta: 0.0  # weight for the KL loss term (needs to be tuned)

### dataset
dataset: openr1_hard_sft
template: qwen
overwrite_cache: true
cutoff_len: 10240
preprocessing_num_workers: 32
dataloader_num_workers: 8
cache_dir: ~/cth/LLaMA-Factory/data

### output
output_dir: /data/cth/saves/Qwen2.5-Math-7B/full/sft_curr_part3
logging_steps: 10
save_steps: 94
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: [wandb]  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

### test
# do_test: true
# test_steps: 500
# test_input_file: ~/cth/LLaMA-Factory/data/valid.all.parquet
# test_output_file: ~/cth/LLaMA-Factory/results/Qwen2.5B-Math-7B/Qwen2.5B-Math-7B-kl.log
# test_debug: false
# test_remove_system: true
# test_template: qwen
# test_temperature: 0.6
# test_top_p: 1.0
# test_max_tokens: 8192
